services:
  frontend:
    image: next:dev
    container_name: next-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    restart: always
    ports:
      - 3000:3000
    networks:
      - internal

  backend:
    image: strapi:dev
    container_name: strapi-app
    build:
      context: ./backend
      dockerfile: Dockerfile
        #target: dev
      args:
        - NODE_ENV=${ENVIRONMENT}
    env_file:
      - .env
      - ./backend/.env
    volumes:
      - ./backend:/app
    restart: always
    ports:
      - "1337:1337"
    networks:
      - internal
    depends_on:
      - postgres

  postgres:
    image: postgres:12.0-alpine
    #container_name: ${PROJECT_SLUG}_postgres
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data/ #using a volume
    networks:
      - internal

networks:
  internal:
    driver: bridge
